### ISSUE TITLE
Stopped Working suddenly

### ISSUE THREAD

**Issue by Majora-Luna** [andresdavid90/tumblr-lks-downldr-cli#10]
I had the batch file working perfectly for a while but a few days ago it stopped working suddenly. When I run the command/batch, the window disappears with just the message "downloading 0 files". 

I had nodeJS v 6.9.2 x64 and thought maybe that would be the issue so first I repaired/reinstalled it, no go, then uninstalled it to install the next stable version available, 6.9.4 x64, and no go. So I'm at a loss now. (Note: if anyone intends on downloading from the tumblr listed in this screenshot for any reason, be warned that there is NSFW stuff!) 

I had quotation marks around the tumblr URL and the folder name but I removed them while attempting to troubleshoot. Same result with or without "quotation marks" around the blog URL and the "Tumblr" word at the very end of the command.

![screenshot 2017-01-18 20 10 46](https://cloud.githubusercontent.com/assets/22646502/22090998/14ce54c0-ddba-11e6-93ee-2124d5d00218.png)

**Comment by andrscrrn** [comment]
I'll check today and I'll let you know what I find.

**Comment by andrscrrn** [comment]
@Majora-Luna please check your settings and enable "Share posts you like".
<img width="678" alt="screen shot 2017-01-24 at 9 51 19 pm" src="https://cloud.githubusercontent.com/assets/1095614/22279381/5a037cb8-e27f-11e6-8163-c05741260426.png">
