### ISSUE TITLE
Not downloading all likes

### ISSUE THREAD

**Issue by nilsbyte** [andresdavid90/tumblr-lks-downldr-cli#2]
Node.js of 4.4.2 LTS
tumblr-lks-downldr-cli 1.0.1
Mac OS X 10.11.4

Your tool is counting over 3800 likes which is correct but it only saves 181 of them in the defined folder. It displays all 3800+ urls in the terminal output... thats wrong here?

**Comment by andrscrrn** [comment]
Hi @nilsbyte. Can you please provide the url that you're using?
