### ISSUE TITLE
Add attribution option

### ISSUE THREAD

**Issue by derikb** [andresdavid90/tumblr-lks-downldr-cli#7]
To coincide with 1.5.0 of tumblr-lks-downldr-cli

Sorry, I just merged this to master without asking. Thought I was on my fork and was going to do a pull request. Just a minor change to pass along the attributes param. Tested with and without it and it works fine.

I bumped the version to 2.2.0, I won't publish to npm until you confirm.

**Comment by andrscrrn** [comment]
No worries. I just checked and yes, it seems to be fine. Publishing! 👍
