### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by Majora-Luna** [andresdavid90/tumblr-lks-downldr-cli#8]
![screenshot 2016-10-05 15 26 35](https://cloud.githubusercontent.com/assets/22646502/19130234/f7115a1a-8b0f-11e6-9570-919f8bcb695f.png)

I don't know if there's a setting on my tumblr or anything I have to change but this is the result. 

Fresh install of Node.js

did "npm install tumblr-lks-downldr-cli -g"

**Comment by derikb** [comment]
Do you have your Tumblr set so Likes are public?

**Comment by Majora-Luna** [comment]
After some brief research into that (because I couldn't find any option explicitly for making likes public or not) I conclude that they are set to public. I even tried accessing my likes from a different browser (one where i'd never logged into tumblr from) and they're fully visible.

**Comment by derikb** [comment]
Works for me. Maybe it's a firewall problem or maybe it's a Windows problem. "Unreachable" would seem to indicate some kind of network issue.

**Comment by Majora-Luna** [comment]
Oh. What port(s) does this use if not the regular HTTP(80) one? Maybe I can fiddle with port forwarding. 

I'm not sure if I could add a firewall exception since there doesn't seem to be a specific .exe to add an exception for (adding it for "cmd.exe" seems excessive and probably wouldn't work but I'll try that temporarily at least). Tried disabling my antivirus for a sec and that changed nothing so it might be firewall.

**Comment by Majora-Luna** [comment]
Update: 

So to be sure I ran the command prompt as administrator, but I do not know if this had anything to do with it.

BUT turns out the instructions (on the main project page here) is a little misleading. The URL is shown to be encased with 'these' marks but in reality you need "quotation" marks. As far as I can tell this was my only problem but after using quotation marks it is downloading things.

**Comment by andrscrrn** [comment]
@Majora-Luna Oh well, I wasn't sure that it was a Windows issue. Can you please confirm that now it is working properly? So I can close this issue.

**Comment by Majora-Luna** [comment]
Yeah it works. Had to use quotation marks instead of whatever 'these' are called. No problem after all. Sorry xD

**Comment by derikb** [comment]
I don't think it was the single quotes that were the problem, it was that you were using "smart" ones. Not the difference between straight ones and curved ones. (Unless that's just a really weird font in your command prompt.
