### ISSUE TITLE
Unreachable posts

### ISSUE THREAD

**Issue by ashhashh** [andresdavid90/tumblr-lks-downldr-cli#9]
Hey! Thank you for your script, I'm kind of a noob and this was surprisingly easy to use, but it doesnt download all of my likes, yesterday was only 90, and now it's only 54. The ones from today are the posts that I liked in the previous hour. I have no idea what's going on. Would you ?

Thanks!

**Comment by ashhashh** [comment]
(btw, it works for other blogs, just not for mine…)

**Comment by andrscrrn** [comment]
@ashhashh can you please provide the URL that you are trying?

**Comment by ashhashh** [comment]
It's cowboytaco.tumblr.com

**Comment by ashhashh** [comment]
@andrscrrn So I've tried again and it basically just downloads the last posts I liked, but the rest is "unreachable"…

**Comment by andrscrrn** [comment]
@ashhashh can you please confirm the Node version that you are using? I'm trying to run the tool with Node 7 and I can already see that is not working as expected...

**Comment by andrscrrn** [comment]
@ashhashh I double checking using Node 6 and it's just getting stuck or very slow. The only thing that I can think right now, is that the problem is in the Tumblr servers but I'm not totally sure. I'm going to start monitoring each day how it works to define if the problem is in the tool or on the servers.

**Comment by ashhashh** [comment]
@andrscrrn Thank you for taking the time to look into it… 
I'm using the 6.9.2 version.

It's really weird cause I also tried to use it with the tumblr link you provided in your script as well as with other urls and it's working perfectly. And when I launch it with mine, it just downloads about 200 posts and then stops, telling the rest in unreachable.

**Comment by andrscrrn** [comment]
@ashhashh I think it is actually a problem in the script. I'm currently checking the code so I hope to fix it or give you the reason of why it is failing soon.

**Comment by ashhashh** [comment]
Ok well thank you very much for taking the time to look into it !

**Comment by andrscrrn** [comment]
@ashhashh Hey, please uninstall the module with `npm uninstall tumblr-lks-downldr-cli -g` and then install it again with `npm install tumblr-lks-downldr-cli -g`. I just released a new version that should be working better. You can still have issues about unreachable posts, but now that would be a Tumblr API issue and not the module. Please refer to: https://github.com/andrscrrn/tumblr-lks-downldr/issues/15
